#!/bin/bash

volume_percent=$(pactl get-sink-volume @DEFAULT_SINK@ | cut -s -d/ -f2 | tr -d " %")
volume_mutestatus=$(pactl get-sink-mute @DEFAULT_SINK@ | cut -d" " -f2)

if [[ $volume_percent -eq 0 ]] || [[ $volume_mutestatus == "yes" ]]
then
    echo ""
elif [[ $volume_percent -gt 0 ]] && [[ $volume_percent -le 33 ]]
then
    echo ""
elif [[ $volume_percent -gt 33 ]] && [[ $volume_percent -le 66 ]]
then
    echo ""
elif [[ $volume_percent -gt 66 ]]
then
    echo ""
fi


# The percentage of the volume is added to the output.
#if [[ $volume_percent -eq 0 ]] || [[ $volume_mutestatus == "yes" ]]
#then
#    echo " ${volume_percent}%"
#elif [[ $volume_percent -gt 0 ]] && [[ $volume_percent -le 33 ]]
#then
#    echo " ${volume_percent}%"
#elif [[ $volume_percent -gt 33 ]] && [[ $volume_percent -le 66 ]]
#then
#    echo " ${volume_percent}%"
#elif [[ $volume_percent -gt 66 ]]
#then
#    echo " ${volume_percent}%"
#fi
